apiVersion: v1
kind: Service
metadata:
  name: deployment-pv-service
spec:
  selector:
    app: deployment-pv
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pv
  labels:
    app: deployment-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-pv
  template:
    metadata:
      labels:
        app: deployment-pv
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - name: pv-hostpath
          mountPath: /etc/nginx/conf.d/
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 1000Mi
            cpu: 1000m
          requests:
            memory: 500Mi
            cpu: 500m 
      volumes:
      - name: pv-hostpath
        persistentVolumeClaim:
          claimName: pvc-hostpath
      restartPolicy: Always
      terminationGracePeriodSeconds: 30 # equals a 'kill -9'







