apiVersion: v1
kind: Pod
metadata:
  name: pod-service
  labels:
    name: pod-service
    app: myapp
spec:
  containers:
  - name: pod-service
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
