apiVersion: v1
kind: Service
metadata:
  labels:
    run: event
  name: event
  namespace: default
spec:
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    run: event
  sessionAffinity: ClientIP
  type: ClusterIP
