apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob

spec:  
  schedule:  "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Welcome; sleep 30
            