apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - mountPath: /cache
      name: cahce-volume
    ports:
    - containerPort: 80
  volumes:
  - name: cache-volume
    emptyDir: {}
       