apiVersion: v1
kind: Pod
metadata:
  name: podNotPersistent
  labels:
    name: podNotPersistent
spec:
  containers:
  - name: podNotPersistent
    image: ububtu
    volumeMounts:
    - mountPath: /cache
      name: cahce-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
  volumes:
  - name: cache-volume
    emptyDir: {}
       