apiVersion: v1
kind: Service
metadata:
  name: default-backend-service
  namespace: ingress
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: default-backend
    
