apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-secret-env
spec:
  selector:
    matchLabels:
      app: deployment-secret-env
  template:
    metadata:
      labels:
        app: deployment-secret-env
    spec:
      containers:
      - name: deployment-secret-env
        image: redis
        env:
          - name: mysecret
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      
