apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /tmp/giropops
      name: my-secret-volume 
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret 